// plugins.config.js
export default {
	plugins: [
		'collaborative_viewers/bibtex',
		'collaborative_viewers/drawio',
		'collaborative_viewers/tikz',
		'collaborative_viewers/milkdown',
		'viewers/bibtex',
		'viewers/image',
		'viewers/media',
		'viewers/pdf',
		'viewers/drawio',
		'viewers/tikz',
		'viewers/milkdown',
		'renderers/pdf',
		'renderers/canvas',
		'loggers/latex_visualizer',
		'loggers/typst_visualizer',
		'bibliography/zotero',
		'bibliography/openalex',
		'backup/github',
		'backup/gitlab',
		'backup/forgejo',
		'backup/gitea',
		'themes/texlyre_slim',
		'themes/texlyre_wide',
		'themes/texlyre_mobile',
	],
};
